/* Formatted on 07/10/2015 7:03:47 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
--SQL Statement which produced this data:
--
--  SELECT
--     ROWID, ID, SIGLAS, DESCRIPCI,
--     FECHA_INI, FECHA_FIN
--  FROM PLANIFICA.P01_PROYECTO;
--
SET DEFINE ~


SELECT '~~v_SIGLAS.' FROM DUAL;

SELECT '~~v_DESCRIPCI.' FROM DUAL;

INSERT INTO PLANIFICA.P01_PROYECTO (SIGLAS, DESCRIPCI, FECHA_INI)
     VALUES ('~~v_SIGLAS.', '~~v_DESCRIPCI.', SYSDATE);

BEGIN
   IF TRIM (UPPER ('~~GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/