/* Formatted on 07/10/2015 14:09:50 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
SET DEFINE ~

COLUMN idp HEADING "ID" FORMAT A10  TRUNC  NEW_VALUE v_idp
COLUMN DESCRIPCI HEADING "DESCRIPCI" FORMAT A10  TRUNC  NEW_VALUE V_DESCRIPCI


SELECT P01_PROYECTO.ID idp,
       P01_PROYECTO.SIGLAS,
       P01_PROYECTO.DESCRIPCI,
       P01_PROYECTO.FECHA_INI,
       P01_PROYECTO.FECHA_FIN
  FROM PLANIFICA.P01_PROYECTO
 WHERE     UPPER (P01_PROYECTO.DESCRIPCI) LIKE
              UPPER ('%~~v_nombre_proyecto.%')
       AND ROWNUM = 1;

PAUSE EL PROYECTO ES: ~~V_DESCRIPCI


SELECT '~~v_DESCRIPCIN_ACTIVIDAD.' FROM DUAL;

INSERT INTO PLANIFICA.P04_ACTIVIDAD (ID_PROYECTO,
                                     DESCRIPCIÓN,
                                     FECHA_INICIO_PLANIFICADA,
                                     FECHA_FIN_PLANIFICADA)
        VALUES (
                  '~~v_idp',
                  '~~v_DESCRIPCIN_ACTIVIDAD.',
                  TO_DATE (
                     '~~MES_NUMERO/~~DIA_NUMERO/~~ANIO_NUMERO 00:00:00',
                     'MM/DD/YYYY HH24:MI:SS'),
                  NULL);


BEGIN
   IF TRIM (UPPER ('~~GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/