/* Formatted on 07/10/2015 13:58:10 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF

SET DEFINE ~

COLUMN idp HEADING "ID" FORMAT A10  TRUNC  NEW_VALUE v_idp
COLUMN DESCRIPCI HEADING "DESCRIPCI" FORMAT A10  TRUNC  NEW_VALUE V_DESCRIPCI


SELECT P01_PROYECTO.ID idp,
       P01_PROYECTO.SIGLAS,
       P01_PROYECTO.DESCRIPCI,
       P01_PROYECTO.FECHA_INI,
       P01_PROYECTO.FECHA_FIN
  FROM PLANIFICA.P01_PROYECTO
 WHERE     UPPER (P01_PROYECTO.DESCRIPCI) LIKE
              UPPER ('%~~v_nombre_proyecto.%')
       AND ROWNUM = 1;



PAUSE USTED HA SELECCIONADO EL PROYECTO: ~~V_DESCRIPCI;

COLUMN ID FORMAT A15 TRUNC NEW_VALUE V_ID
COLUMN CC FORMAT A15 TRUNC NEW_VALUE V_CC
COLUMN ENCARGADO FORMAT A15 TRUNC NEW_VALUE V_ENCARGADO


SELECT P02_AREA_RECURSO.ID,
       P02_AREA_SERVICIO.DESCAREA,
       P02_RECURSO_HUMANO.CC,
       P02_RECURSO_HUMANO.ENCARGADO
  FROM PLANIFICA.P02_AREA_RECURSO,
       PLANIFICA.P02_AREA_SERVICIO,
       PLANIFICA.P02_RECURSO_HUMANO
 WHERE     UPPER (P02_RECURSO_HUMANO.ENCARGADO) LIKE
              UPPER ('%~~v_v_apellido.%')
       AND P02_AREA_SERVICIO.ID = P02_AREA_RECURSO.ID_AREA
       AND P02_RECURSO_HUMANO.ID = P02_AREA_RECURSO.ID_RECURSO;


PAUSE seleccione el codigo de la persona


SELECT '~~v_codigo_id_generado.' FROM DUAL;


PAUSE

INSERT INTO PLANIFICA.P03_PERSONA_PROYECTO (ID_PROY, ID_AREA_RECURSO)
     VALUES ('~~v_idp.', '~~v_codigo_id_generado.');

SET DEFINE ~

SELECT P01_PROYECTO.SIGLAS,
       P01_PROYECTO.DESCRIPCI,
       P02_AREA_SERVICIO.DESCAREA,
       P02_RECURSO_HUMANO.CC,
       P02_RECURSO_HUMANO.ENCARGADO
  FROM PLANIFICA.P02_RECURSO_HUMANO,
       PLANIFICA.P02_AREA_SERVICIO,
       PLANIFICA.P02_AREA_RECURSO,
       PLANIFICA.P01_PROYECTO,
       PLANIFICA.P03_PERSONA_PROYECTO
 WHERE     P03_PERSONA_PROYECTO.ID_PROY = '~~v_idp.'
       AND ID_AREA_RECURSO = '~~v_codigo_id_generado.'
       AND P02_AREA_SERVICIO.ID = P02_AREA_RECURSO.ID_AREA
       AND P02_RECURSO_HUMANO.ID = P02_AREA_RECURSO.ID_RECURSO
       AND P02_AREA_RECURSO.ID = P03_PERSONA_PROYECTO.ID_AREA_RECURSO
       AND P01_PROYECTO.ID = P03_PERSONA_PROYECTO.ID_PROY;

BEGIN
   IF TRIM (UPPER ('~~GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/