/* Formatted on 07/10/2015 7:16:16 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF

SET DEFINE ~


SELECT '~~v_DESCAREA.' FROM DUAL;


INSERT INTO PLANIFICA.P02_AREA_SERVICIO (ID, DESCAREA)
     VALUES (1, '~~v_DESCAREA.');


BEGIN
   IF TRIM (UPPER ('~~GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/