/* Formatted on 07/10/2015 13:17:37 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF

SET DEFINE ~

COLUMN ID FORMAT A10 TRUNC NEW_VALUE V_ID
COLUMN DESCAREA FORMAT A30 TRUNC NEW_VALUE V_DESCAREA



SELECT *
  FROM PLANIFICA.P02_AREA_SERVICIO
 WHERE     UPPER (P02_AREA_SERVICIO.DESCAREA) LIKE UPPER ('%~~v_DESCAREA.%')
       AND ROWNUM = 1;


PAUSE USTED HA SELECCIONADO ~~V_DESCAREA.

COLUMN ID FORMAT A15 TRUNC NEW_VALUE V_ID_RECURSO
COLUMN CC FORMAT A15 TRUNC NEW_VALUE V_CC
COLUMN ENCARGADO FORMAT A15 TRUNC NEW_VALUE V_ENCARGADO

SELECT P02_RECURSO_HUMANO.ID,
       P02_RECURSO_HUMANO.CC,
       P02_RECURSO_HUMANO.ENCARGADO
  FROM PLANIFICA.P02_RECURSO_HUMANO
 WHERE UPPER (P02_RECURSO_HUMANO.ENCARGADO) LIKE UPPER ('%~~v_ENCARGADO.%');


PAUSE LA PERSONA QUE SE VA A ASIGNAR ES ~~V_ENCARGADO



INSERT
  INTO PLANIFICA.P02_AREA_RECURSO (P02_AREA_RECURSO.ID_AREA,
                                   P02_AREA_RECURSO.ID_RECURSO)
VALUES ('~~V_ID.', '~~V_ID_RECURSO.');


SELECT P02_AREA_RECURSO.ID_AREA,
       P02_AREA_RECURSO.ID_RECURSO,
       P02_AREA_SERVICIO.DESCAREA,
       P02_RECURSO_HUMANO.CC,
       P02_RECURSO_HUMANO.ENCARGADO
  FROM PLANIFICA.P02_AREA_RECURSO,
       PLANIFICA.P02_AREA_SERVICIO,
       PLANIFICA.P02_RECURSO_HUMANO
 WHERE     P02_AREA_RECURSO.ID_AREA = '~~V_ID.'
       AND P02_AREA_RECURSO.ID_RECURSO = '~~V_ID_RECURSO.'
       AND P02_AREA_SERVICIO.ID = P02_AREA_RECURSO.ID_AREA
       AND P02_RECURSO_HUMANO.ID = P02_AREA_RECURSO.ID_RECURSO;

BEGIN
   IF TRIM (UPPER ('~~GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/