/* Formatted on 07/10/2015 15:15:42 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF


SET DEFINE ~

COLUMN idproyecto HEADING "idproyecto" FORMAT A20  TRUNC  NEW_VALUE V_idproyecto


SELECT P01_PROYECTO.ID idproyecto,
       P01_PROYECTO.SIGLAS,
       P01_PROYECTO.DESCRIPCI,
       P01_PROYECTO.FECHA_INI,
       P01_PROYECTO.FECHA_FIN
  FROM PLANIFICA.P01_PROYECTO
 WHERE UPPER (P01_PROYECTO.DESCRIPCI) LIKE UPPER ('%~~v_DESCRIPCI.%');

PAUSE

COLUMN IDACTIVIDADASIGNADA HEADING "IDACTIVIDADASIGNADA" FORMAT A10  TRUNC  NEW_VALUE V_IDACTIVIDADASIGNADA


SELECT P03_PERSONA_PROYECTO.ID IDACTIVIDADASIGNADA,
       P02_AREA_SERVICIO.DESCAREA,
       P02_RECURSO_HUMANO.ENCARGADO
  FROM PLANIFICA.P03_PERSONA_PROYECTO,
       PLANIFICA.P02_AREA_RECURSO,
       PLANIFICA.P02_RECURSO_HUMANO,
       PLANIFICA.P02_AREA_SERVICIO
 WHERE     P02_AREA_RECURSO.ID = P03_PERSONA_PROYECTO.ID_AREA_RECURSO
       AND P02_RECURSO_HUMANO.ID = P02_AREA_RECURSO.ID_RECURSO
       AND P02_AREA_SERVICIO.ID = P02_AREA_RECURSO.ID_AREA
       AND P03_PERSONA_PROYECTO.ID_PROY = '~~V_idproyecto';

PAUSE REVISE EL RECURSO QUE SE VA A ASIGNAR A LA ACTIVIDAD



SELECT '~~ID_ENCARGADO_CON_ACTIVIDAD' FROM DUAL;



SELECT *
  FROM PLANIFICA.P04_ACTIVIDAD
 WHERE     P04_ACTIVIDAD.ID_PROYECTO = '~~V_idproyecto'
       AND UPPER (P04_ACTIVIDAD.DESCRIPCIÓN) LIKE
              UPPER ('~~ID_ENCARGADO_CON_ACTIVIDAD');